timholy/ProgressMeter.jl

src/ProgressMeter.jl

Also defaults solidglyph to the Unicode code point █
U+2588 FULL BLOCK

Allow filled and empty glyphs to be specified as parameters to barstring()

---

src/ProgressMeter.jl
test/test.jl

Thanks for this great package! 
In one of my projects, I know approximately how many iterations a while loop is going to take but I often over-shoot or under-shoot the actual value by a little bit. This patch makes the output of ProgressMeter look sane in either case: when over-shooting, it won't print out the final "Progress: 1XX%" line more than once. When under-shooting, you can now call `finish!` to fast-forward the progress meter to 100% at the end of the loop. The tests I added give examples of both applications.

Only print final status message once, add finish! method to fast-forward progress meter

---

src/ProgressMeter.jl

to fix "WARNING: Base.String is deprecated, use AbstractString instead." in Julia 0.4.0-rc2+10.
Pkg.test did pass on Julia 0.3.12-pre+5 and 0.4.0-rc2+10.

replaced String by AbstractString

---

src/ProgressMeter.jl

This lets `printover` work as intended within ESS.
Note that one case where it still doesn't work is running `Pkg.test("ProgressMeter")` within ESS. However `include("runtests.jl")` works fine.

Use appropriate control character within ESS

---

REQUIRE
src/ProgressMeter.jl

As I mentioned in #18, it would be worth unifying two inner constructors into an inner constructor using keyword arguments to make it easy to set some of the parameters and keeping backward compatibility; this is a working implementation of it.
But before finishing my job, let me ask a few questions.
1. Why the original two constructors specify different `dt` values (`1.0` vs. `0.01`)?
2. Again, why `barlen` is set to different values between the two constructors (`0` vs. tty width)?
If there is no reason to do so, I think setting a same value would be better.

WIP: unified constructor with keyword arguments

---

.travis.yml
README.md
REQUIRE
src/ProgressMeter.jl
test/test.jl

Some tasks, like minimizing a function, often take an indeterminate number of iterations: for example, one might iterate a L-BFGS step until the function value stops changing by more than `thresh`, and it's not predictable how many iterations this will take. This PR adds an alternative type of progress meter customized for such settings.
Example of output during the computation:
```
Computing nonnegative factorization: (thresh = 1e-07, value = 2.84137e-6)
```
Example of output once `value` drops below `thresh`:
```
Computing nonnegative factorization: Time: 0:00:09 (164 iterations)
```

Add docstrings and a progress meter based on a threshold

---

src/ProgressMeter.jl

First of all I want to say I love this package. I use it all the time.
I have some computations where the first few iterations have some additional overhead that pushes the ETA over 10 days. In this case the progress meter over flows onto a second line (if you use `tty_width` as the bar length). This PR simply reduces the length of the ETA string in this case. As a result the ETA is less precise, but I don't think you are usually very interested in the number of seconds when your ETA is over 10 days anyway.
*Example output now:*
```
julia> using ProgressMeter
julia> N = 10000000
p = Progress(N, "Progress: ")
for idx = 1:N
sleep(0.5)
next!(p)
end
Progress:   0%|                              |  ETA: 61.17 days
```

Shorten the ETA string when t >= 10 days.

---

src/ProgressMeter.jl

The PR just removes the code that hides the cursor. An alternative would be to restore the cursor state after the progress is done, but it still would not handle `Ctrl+C` cases.

Fix hidden cursor after the progress with showvalues=

---

REQUIRE
src/ProgressMeter.jl

* abstract type declaration (requires Compat 0.17)
* inner constructor syntax
Note: Tests are still expected to fail on 0.6 pending #65.

Fix Julia 0.6 deprecations

---

src/ProgressMeter.jl
test/test.jl

Dict comprehensions are gone in 0.6, replaced with a "generator" syntax. Since `@showprogress` does not support generators (yet), I've simply disabled these tests on julia 0.6.

Remove `@showprogress` tests for dict comprehensions on julia 0.6

---

src/ProgressMeter.jl

Without this, `@showprogress for ...` would show a progress bar, but `@showprogress dt for ...` would not.

make default barlen consistent

---

src/ProgressMeter.jl

This fixes https://github.com/tpapp/julia-repl/issues/13 using the solution
already employed by `Base.Terminals`, see
https://github.com/JuliaLang/julia/commit/c9f28da19bfe061280fa91120c08ee851e1ff31e
I am not an expert on terminal control characters, but since it is used by Base
it must have seen a lot of testing so I assume it is correct. I tested on Linux,
using various terminals (also with tmux), and ansi-term inside Emacs, and
existing behavior is maintained.
(the neatest solution, of course, would be factoring out the control characters
in Base.Terminals in such a way that they could be sent to any `::IO`, this is but
a quick workaround).

Replace control char \u1b[A with \r.

---

REQUIRE
src/ProgressMeter.jl
test/test.jl

This requires https://github.com/JuliaLang/Compat.jl/pull/481 which I have tentatively assumed to be included in a future Compat 0.52. (Tests will fail immediately due to Compat 0.52 not being available, yet).

Deprecation fixes for Julia 0.7

---

REQUIRE
src/ProgressMeter.jl
test/test.jl

Again, this depends on a not-yet-merged feature of Compat which I tentatively assume to be included in the next Compat version. (Tests pass locally when checking out the respective branch of Compat.)

Use `stderr` instead of `STDERR` on newer Julia

---

README.md

This adds some tips to the readme to help people with parallel computing (e.g. #96 and #97). The new text is as follows:
When multiple processes or tasks are being used for a computation, the workers should communicate back to a single task for displaying the progress bar. This can be accomplished with a `RemoteChannel`:
```julia
using ProgressMeter
using Distributed
p = Progress(10)
channel = RemoteChannel(()->Channel{Bool}(10), 1)
@sync begin
@async while take!(channel)
next!(p)
end
@async begin
@distributed (+) for i in 1:10
sleep(0.1)
put!(channel, true)
i^2
end
put!(channel, false) # this tells the printing task to finish
end
end
```

added parallel tips

---

src/ProgressMeter.jl

I noticed that in Atom the first line of the progress bar wasn't printed with color (but additional values provided by `showvalues` are). With this also the first line is now printed with color.

Fix dropping of color in printing of the first line in Atom

---

README.md
src/ProgressMeter.jl
test/test.jl
test/test_showvalues.jl

This is a follow up to #115. I noticed that I missed two use cases
1) Sometimes you want to increase the counter by more than 1 or even decrease it again
2) Sometimes you want to update additional informations displayed by `showvalues` but not the counter
Both are fixed by adding the possibility to set the counter manually (by the same API as `Progress` already uses).

Make it possible to set the counter in `ProgressUnknown` by hand.

---

README.md
src/ProgressMeter.jl
test/test.jl

Enables slightly smoother progress bar which is nice when the width is not so big.
Link to asciinema below (they seem to have some bug in their monofont width rendering so it shifts a bit but this doesn't happen in the terminal):
https://asciinema.org/a/2BSeu9De6gO8UC05B0jDDx0jI
The first three bars are with a transition and the last one is with the current default.

allow one to transition between empty and full

---

src/ProgressMeter.jl
test/core.jl
test/runtests.jl
test/test.jl

Hi, please take a glance at the screenshot here.
The displayed time in seconds has been rounded up to "60" if it was larger than 59.5. This pr fix this.

Fix the elapsed time displaying

---

src/ProgressMeter.jl

By default now whenever this prints the progress meter, it will also flush the stream (see #117). Does everyone else think this is a good idea? Perhaps there are unforeseen consequences of flushing that I have not thought of.

added alwaysflush option to fix #117

---

src/ProgressMeter.jl

Surprisingly, the argumentless default returns the values of the environment variables `ROWS` and `COLUMNS`, which (at least on gnome-terminal) are not necessarily up-to-date with window resizes.
Adding `stdout` gives a result that corresponds to current size.
This prevents the following situation:
A followup feature could be to poll this width to stay up-to-date with window resizes.

Use stdout's displaysize for size computation

---

.gitignore
.travis.yml
Project.toml

The downside at present is that releases require manually bumping the version here in addition to tagging/creating a release on Github. As releases here don't occur too often, that should hopefully be OK. We might also immediately bump the version as part of this PR and and tag a release. Extrapolating from the API stability this package was able to maintain in the past, calling it 1.0.0 might be an option.

RFC: Add Project.toml and set version to 1.0.0

---

README.md
src/ProgressMeter.jl
test/test.jl

I find that I often want to use `@distributed` loops with a reducer to compute a result. The code in the "tips for parallel programming" section of the README works well so thought I'd make a macro out of it. If there is a reason for not wanting to put the code from the README in the package then feel free to ignore/close this request.

make @showprogress work with @distributed

---

.travis.yml
README.md
src/ProgressMeter.jl
test/runtests.jl
test/test_threads.jl

Trying out @KristofferC's suggestion in #139 of just spinlocking by default.
All tests pass locally for me!
```julia
n = 100
p = ProgressMeter.Progress(n)
Threads.@threads for i = 1:(n)
sleep(0.1)
ProgressMeter.next!(p)
end
```
I didn't figure out getting `@showprogress` working, but I assume it would follow something like intercepting `@threads` and passing to a custom `showprogressthreads`?

Add spinlocking for core methods, to support threading (alt to #139)

---

src/ProgressMeter.jl

I was surprised that a function like `foo() = @showprogress for i in 1:10^7; rand(); end` produced 10^7 allocations. The reason, it seems, is the `showvalues = Any[]` kwarg default. I'm not sure why it is written like this, but making it an empty tuple removes one allocation per iteration, and moreover cuts the runtime overhead dramatically
Master
```
julia> @time foo()
Progress: 100%|███████████████████████████████████████| Time: 0:00:00
0.831637 seconds (10.00 M allocations: 762.963 MiB, 14.18% gc time)
```
PR:
```
julia> @time foo()
Progress: 100%|███████████████████████████████████████| Time: 0:00:00
0.411675 seconds (232 allocations: 13.703 KiB)
```

Avoid allocations due to kwarg default showvalues = Any[]

---

src/ProgressMeter.jl
test/test.jl

I often have a situation in which I am doing an optimization problem with some convergence threshold, so I use `ProgressThresh`. This works great:
```julia
julia> optimize(foo, bar)
Maximizing: Time: 0:00:05 (388 iterations)
[ Info: Successfully converged after 388 iterations
```
However, sometimes I also want to enforce a maximum number of iterations, after which I will terminate even if I have not converged. In order to terminate the progress bar in those cases, I call `finish!`, and then I print a warning to the user. Unfortunately, when I call `finish!` on `ProgressThresh`, it increments the counter, even though I did not actually perform an additional iteration. So the output looks like this:
```julia
julia> optimize(foo, bar; max_iterations = 100)
Maximizing: Time: 0:00:01 (101 …
```

Ability to update and finish `ProgressThresh` without incrementing the counter

---

src/ProgressMeter.jl

An omission from #159 
The bar length wasn't updated to adjust for the different description length, which if the new description was longer could cause the progress bar to spill onto a 2nd line, breaking the in-place update of the progress bar.
This corrects for any change in description length during the `update!`

Adjust bar length to accommodate updated description

---

Project.toml
README.md
src/ProgressMeter.jl
test/test_map.jl

The current mechanism already works with `reduce` perfectly, so I just relax the assertion to allow `:reduce` and add some test cases for it.

make showprogress work with reduce

---

src/ProgressMeter.jl
test/test_showvalues.jl

Allows for a dynamic terminal width, fixing issues with line wrapping and allows for truncating of a showvalues line.
Does 3 related things:
1. Calculates `barlen` during the run, so that resizing the terminal is noticed.
2. Does not assume a showvalues line is only 1 line long.
3. Adds in a `truncate_lines` option for `update!` to force a showvalues line to be only 1 line long. This gives something like:
```
Progress: 100%|███████████████████████████████████████| Time: 0:00:20
message:   0123∀ x ∃ y4567890123∀ x ∃ y4567890123∀ x ∃ y4567890123∀ x ∃ y45…
sentence:  Dolor et alias culpa quod ab maiores tenetur aut expedita nisi v…
```
I haven't tested this on Atom or Jupyter as I don't have them installed currently. As long as they give sensible values for `displaysize(p.output)`, I hope …

Dynamic terminal width

---

src/ProgressMeter.jl
test/core.jl

The `io::IO` field still needs to be abstract, but I don't think there's a good reason for `desc` to be. Does anyone know of a reason to keep it `AbstractString`?

Use concrete fields where possible

---

src/ProgressMeter.jl

This PR fixes #171. Most of the time in `updateProgress!` is now spent in `time()` which I guess is unavoidable.

Improve performance of `updateProgress!`

---

README.md
src/ProgressMeter.jl

This PR detects if the IO is a file or TTY and prevents printing the progress bars to file in cases like when running in an HPC with a SLURM schedule that the logs get full of noisy output.

make output optional

---

README.md
src/ProgressMeter.jl
test/test_showvalues.jl

Hi, 
`update!` and `next!` are methods so its arguments will be evaluated in every call. 
Sometimes I want to show values that are computed on the fly, and it is a waste of time to
compute them if the progress won't be reprinted. 
So I just add a version of `printvalues!` that takes a zero-argument function as `showvalues`
so it will be evaluated just in case of re-printing.
An illustrative example
```julia
@info "Current: showvalue evaluates each iter"
@time let
prog = Progress(10; dt = 1.0);
for i = 1:10
sleep(3/10) # add 3 seconds
next!(prog; showvalues = [
("heavy val", (sleep(3/10); i)) # adds 3 additional seconds
]
)
end
finish!(prog)
end
#= 
[ Info: Current: showvalue evaluates each iter
Progress: 100%|█████████████████████████████| Time: 0:00:06
heavy val:  10
6.289688 seconds …
```

Allow passing a function for lazy-showvalues

---

src/ProgressMeter.jl
test/core.jl

`running_ijulia_kernel()` and `clear_ijulia()` are not inexpensive functions, and they're being polled every update.
This changes them to only be polled during creation of the progress meter, then static bools are used in their place for the rest of the run. 
I don't believe this changes any behavior in IJulia?

Only poll IJulia state during init

---

.github/workflows/ci.yml
src/ProgressMeter.jl

Given the first iteration can be slower in julia due to compilation, it appears to be better to to base the ETA timing off the second iteration onwards.
As an example, take this which has a fake 3 second delay after the progress bar init to simulate some compilation of the loop
```julia
n = 100
p = Progress(n)
sleep(3)
for i = 1:n # 5-second loop
sleep(0.05)
ProgressMeter.next!(p)
end
```
On master, the first ETA to print starts at about 30 seconds, then gradually reduces linearly throughout, decrementing far faster than seconds in real time and never really giving a fair ETA.
In this PR, the first ETA is 4 seconds, and decrements immediately in-step with real-time seconds towards the final completion of 5 seconds. It never seems inaccurate

Base ETA off second iteration onwards for higher accuracy

---

src/ProgressMeter.jl

When `finish!` is called on a `Progress` type meter with a slow update limit and a significant number of steps left, it will max a CPU core while slowly updating the progress meter until it is complete.
MWE:
```julia
julia> p = Progress(100000000; dt=.1);
julia> next!(p); @time finish!(p)
Progress: 100%|██████████████████████| Time: 0:00:16
14.919932 seconds (6.75 k allocations: 357.250 KiB)
```
This took me by surprise, and doesn't match the immediate completion behavior specified in the code for the `finish!` methods for `ProgressThresh` and `ProgressUnknown`.
PR:
```julia
julia> p = Progress(100000000; dt=.1);
julia> next!(p); @time finish!(p)
Progress: 100%|██████████████████████| Time: 0:00:01
0.000068 seconds (43 allocations: 3.422 KiB)
```

Improve `finish!` behavior for `Progress`

---

README.md
src/ProgressMeter.jl
test/core.jl
test/test.jl

*I'm pretty new to Julia (both the language and the community), so please help me understand if I'm not following best practices here.*
As someone coming from the Python ecosystem to Julia, one of the things I missed most from my Python workflows was the the functionality of the [tqdm](https://tqdm.github.io/) package. Though ProgressMeter.jl gives me a lot of what I love about tqdm, I really missed being able to see the rate at which my loops are running. Here's an example of the default tqdm output:
100%|███████████████████████████████▉| 8014/8014 [01:37<00:00, 82.29files/s]
So I got to thinking, maybe I can add this functionality, or at least the part of it I miss. And so I dug into the source and did my best to implement a non-invasive default-off `showspeed` option. For simplicity, I …

Add an option to show per-iteration speed

---

README.md

This fixes #187. The `enabled` keyword argument to allow disabling the progress meter was introduced in #185 but the README wasn't updated to use the `enabled` keyword argument that was settled upon in the PR.
This also removes a spurious `**`.

Fix keyword argument to enable/disable progress meter

---

README.md

This PR improves the [tips for parallel programming](https://github.com/timholy/ProgressMeter.jl#tips-for-parallel-programming) section in the README.
The earlier example in this section was relying on the presence of a `sleep` call, which couldn't be replaced with an actual function out of the box. The new version is using an actual dummy function, which users can replace more easily with something useful.
I was asked to contribute this improvement [in a related issue](https://github.com/timholy/ProgressMeter.jl/issues/136#issuecomment-785020733). However, I am also thinking about implementing a distributed decorator for progress bars, so that all bar types can be used in parallel implementations out-of-the-box.

Improve distributed example with a long-running function instead of sleep

---

test/core.jl

As noted in https://github.com/timholy/ProgressMeter.jl/pull/206#issuecomment-851103843, the github CI machines are too unreliable to do performance comparisons, so this test should be disabled on CI (but still runs when testing locally).

disable performance tests in github CI

---

README.md
src/ProgressMeter.jl

Some README examples do not work because the correct keyword is `enabled`

fix typos related to the 'enabled' keyword

---

README.md
src/ProgressMeter.jl
test/test.jl

This adds a `spinner=true` option to the `ProgressUnknown` case, mimicking the one in Pkg (though you can also customize the spinner characters), inspired by [this discourse thread](https://discourse.julialang.org/t/how-to-print-rotating-tick-as-progress-bar-in-terminal/62099).
Closes #92.

add spinner option to ProgressUnknown

---

src/ProgressMeter.jl
test/core.jl

Intended to fix - #209  (will close if confirmed to be fixed in the next release)
Avoids a NaN which could happen because the print time compensation makes an assumption about how long printing takes, therefore it's possible (but rare) for `t == p.tlast` within `calc_check_iterations`

Avoid rare NaN in calc_check_iterations

---

src/ProgressMeter.jl

I was looking at the Pkg.jl interface again, and I noticed a difference from #206 — it displays the spinner/checkmark to the left of the description, not to the right.
I tried it out in ProgressMeter.jl and it seems to look nicer.  Also, it is nice to be more similar to the Pkg interface.

put spinner to left of description

---

src/ProgressMeter.jl

It doesn't make sense to me that `enabled` stops working as expected in IJulia (ie Progress will always updates/prints in IJulia, regardless of `enabled` value).
Fixes #214

Remove `enabled` dependence on IJulia; fix #214

---

src/ProgressMeter.jl

Currently the `desc` is required to have a trailing space, otherwise you end up with
```
Custom message100%|█████████████████████| Time: 0:00:00
```
This just checks if there is a trailing space and adds one if not.
Intended to be the minimal way to fix this.

Add space after description if needed

---

test/core.jl

By checking the CI env var instead, this also covers PkgEval.
https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_date/2022-10/08/ProgressMeter.primary.log

Generalize CI check in tests.

---

Project.toml
src/ProgressMeter.jl

This PR makes the docstings more consistent with Julia conventions. Without this change, it isn't very clear what arguments are allowed from the docstring alone.

Structure docs more

---

README.md

Hi,
Thanks for a very useful package. I went over the examples in the readme and spotted that a few of the Progress constructors were in the old format (n, dt) instead of (n; dt = dt) so that they would error on master. I also removed dt with the same issue from a call where it isn't really needed for what is being demonstrated.

Update README.md to account for signature change

---

src/ProgressMeter.jl
test/test.jl

This allows constructs such as:
```jl
@showprogress "X: " color=:red for x in 1:10
sleep(1)
end
```
and
```jl
@showprogress showspeed=true for x in 1:10
sleep(1)
end
```
Fixes #229.

Make @showprogress support keyword arguments

---

src/ProgressMeter.jl

Tab skips over anything already on the line rather than printing over it, so if the lengths of the description etc. has changed it caused a mess

Don't use tabs during print because it doesn't work with overprinting

---

README.md
src/ProgressMeter.jl
src/deprecated.jl
test/core.jl
test/deprecated.jl
test/runtests.jl
test/test.jl
test/test_float.jl
test/test_map.jl
test/test_showvalues.jl
test/test_threads.jl

deprecates non-kwargs methods to build progresses and `next!`/`update!`
for example:
```julia
Progress(10; desc="My progress")
ProgressUnknown(desc = "Computing...", color=:red)
next!(p; desc="New description")
update!(p; color=:blue)
```
also adds `max_steps` and `thresh` as kwargs for `next!` and `update!`. I'm not sure about the name `max_steps`, but I don't like `max` or `n`, feel free to suggest something else.
closes #33, closes #160, closes #165, closes #220, closes #225, closes #254, closes #259

Deprecate non-kwargs methods

---

test/test_map.jl

Single-argument `map` is being removed from Julia after an analysis of registered packages found that the change doesn't break the functionality of any package. See JuliaLang/julia#35293 and JuliaLang/julia#52631
That said, the Julia change breaks your test suite, so here's a PR that fixes that.

tests: don't use single-argument `map`

---

test/test_threads.jl

adds locks in test_threads
I don't know much about thread-safety but `push!(vals,rand())` is definitely unsafe and even `sum(vals)` seems to be unsafe
an alternative to locks would be [`atomic_add!`](https://docs.julialang.org/en/v1/manual/multi-threading/#Atomic-Operations)
fix #281

add locks in test_threads

---

src/ProgressMeter.jl
test/test.jl
test/test_threads.jl

This lets you use the @showprogress macro on parallel for loops. For example,
```
@showprogress Threads.@threads for i in 1:100
sleep(0.1)
end
```

add support for using @showprogress on Threads.@threads for loops

---

README.md
src/ProgressMeter.jl
test/test_map.jl

the `@showprogress` macro doesn't check anymore if functions are in a predefined list of allowed functions, instead, `ncalls` should be defined for the used function. This allows to add new map-like function, for example `tmap`:
```julia
using ThreadTools, ProgressMeter
ProgressMeter.ncalls(::typeof(tmap), ::Function, args...) = ProgressMeter.ncalls_map(args...)
ProgressMeter.ncalls(::typeof(tmap), ::Function, ::Int, args...) = ProgressMeter.ncalls_map(args...)
@showprogress tmap(abs2, 1:10^5)
@showprogress tmap(abs2, 4, 1:10^5)
```
fix #144, fix #251

allow for new map-like functions

---

test/test_threads.jl

removes `push!` in threaded code, and avoids the function `is_threading` by adding `p.threads_used = 1:threads` (#232)
(this is not a fix for #232, only so that CI passes)

fix test_threads (hopefully)

---

README.md
src/ProgressMeter.jl
test/core.jl
test/test.jl
test/test_float.jl
test/test_showvalues.jl
test/test_threads.jl

fix #58, fix #267, fix #218
allows for comprehensions with conditions and multiple `for`s
also some refactoring:
- split `showprogress_loop` and `showprogress_map` out of `showprogress`
- remove a lot of useless `ProgressMeter.` in tests

Support more complex comprehensions

---

.github/workflows/ci.yml
Project.toml
src/ProgressMeter.jl

- Drops julia versions <1.6 (very old now, so not worth supporting given even things like `hasfield` aren't defined)
- Reduces code duplication .There's a fair bit of duplication between the three core Progress types. This puts the common elements into a `ProgressCore` struct to avoid duplication.

Drop Julia <1.6. Reduce code duplication by introducing ProgressCore

---

.github/workflows/ci.yml
src/ProgressMeter.jl

Just a minor tidyup after #304

move new funcs

---

src/ProgressMeter.jl
test/core.jl
test/test_float.jl
test/test_threads.jl

fix https://github.com/timholy/ProgressMeter.jl/pull/304#discussion_r1549634629

fix breaking `setproperty!` introduced in #304

---

src/ProgressMeter.jl
test/core.jl
test/test.jl
test/test_threads.jl

This is another possible fix for: https://github.com/timholy/ProgressMeter.jl/issues/317 and https://github.com/timholy/ProgressMeter.jl/issues/232
Here we remove the automatic identification of threading, and always use a lock by default. An option `safe_lock` is added, which is by default `true` and must be set to `false` to disable the lock.
Relative to the current stable version I don't see any measurable performance difference:
Current stable:
```julia
julia> function prog_perf(n)
prog = Progress(n)
x = 0.0
for i in 1:n
x += rand()
next!(prog)
end
return x
end
prog_perf (generic function with 1 method)
julia> @time prog_perf(10^7)
Progress: 100%|█████████████████████████████████████████████████████| Time: 0:00:05
5.938973 seconds (122.22 M allocations: 1.889 GiB, 2.62% gc time, …
```

lock by default - add safe_lock option for control

---

src/ProgressMeter.jl

The PR adds the `force=true/false`  keyword argument to `updateProgress!()` method.
When `force=true`, the progress bar is unconditionally updated regardless the too frequent bar updates check.
*The use case*: I am processing the big data file that I download chunk by chunk (one chunk contains thousands of data entries).
The progress bar reflects how many entries have been processed.
Each datum is processed within fraction of a second.
However, downloading the next chunk of data takes a while (minutes), during which time the progress bar freezes.
I use `showvalues=` to report the current status: either data processing or chunk download.
The problem is that in 99.9% cases the download-related progress bar update gets suppressed by the frequency filter (dt) -- so during the download the bar …

Allow forcing the progress bar update

---

src/ProgressMeter.jl
test/core.jl

use getfield for performance and add performance tests

---

README.md

In the `README.md` example, it used a symbol for the "name" in the `showvalue` argument.   It seems a lot clearer to use a string in the example — not only are strings less obscure than symbols, they are also more flexible and natural as labels.
Internally, the code [calls `string(name)`](https://github.com/timholy/ProgressMeter.jl/blob/45e21fb09fe2196a0ef75690bd96a4fa0d892f45/src/ProgressMeter.jl#L570), so it can be anything.
(Right now, `showvalues` is only documented in the README … would be nice to have this in a docstring somewhere.)

clarify that showvalues "name" can be a string

---

src/ProgressMeter.jl

Before this PR, labels in `showvalues` are left-aligned, which looks weird:
```jl
julia> x,n = 1,10
(1, 10)
julia> p = Progress(n);
julia> for iter in 1:10
x *= 2
sleep(0.5)
next!(p; showvalues = [("iteration count",iter), ("x",x)])
end
Progress: 100%|█████████████████████████████████████████| Time: 0:00:05
iteration count:  10
x:                1024
```
afterwards, they are right-aligned:
```jl
julia> for iter in 1:10
x *= 2
sleep(0.5)
next!(p; showvalues = [("iteration count",iter), ("x",x)])
end
Progress: 100%|█████████████████████████████████████████| Time: 0:00:05
iteration count:  10
x: 1024
```
which seems more readable to me.

right-align labels in showvalues (not left-align)

---

src/ProgressMeter.jl
test/core.jl

with #325, the difference in performance with the `safe_lock` is much more noticeable compared to #322 (x4-5 on my machine) 
this stores only the starting thread instead of a vector of all used threads (which is basically the same)
I can't see a repeatable difference between disabling the lock and letting in detect but both are still possible with this
Performance results from `runtest.jl`: (these numbers vary quite a lot between each run)
```
Performance results:
without progress:      1.23 ns/it
with no lock:          9.23 ns/it
with no printing:      8.85 ns/it
with disabled:         2.60 ns/it
with lock:            41.06 ns/it
with automatic lock:   9.02 ns/it
with lock, disabled:  32.18 ns/it
with force:            0.20 ms/it
Threaded performance results: (4 threads)
without …
```

Return of the threaded detection

---

src/ProgressMeter.jl

Closes #224. That solution only worked if the string was padded to the display width, but this solution should correctly be able to deal with multiline strings.
Here's a demo:
```julia
let n = 20
xs = Float64[]
p = Progress(n)
for iter = 1:n
append!(xs, rand())
sleep(0.5)
plt = lineplot(xs)
ProgressMeter.next!(p; showvalues = [(:UnicodePlot, plt)])
end
end
```
[Screencast_20250402_171908.webm](https://github.com/user-attachments/assets/ba31eae8-4742-4627-b68b-2dc6a1c1fb0e)

Fix printing of multiline values, and allow colors in showed values
