- src/ProgressMeter.jl
This pull request makes the output stream of a progress selectable.
This is especially useful when we want to save an output of a program into a file with redirection and check the progress from our terminal (the `curl` command-line tool works as such):
```
$ julia program.jl > output.txt
```
In this case, you can set the output stream of the progress bar to `STDERR`:
```julia
p = Progress(10)
p.output = STDERR
```
BTW, two constructors of `Progress` look a little bit messy and make it hard to set some parameters.
Can I unify them to a constructor using keyword arguments like `function Progress(n::Integer; dt::Real=1.0, desc::String="Progress: ", and others)` as another pull request?
Of course we will need some outer constructors like `Progress(n::Integer, desc::String)` for backward …
> make the output stream selectable

- README.md
- src/ProgressMeter.jl
Should be clean now ;)
Tests pass as well.
> Added update! method for non-constant progress steps

- src/ProgressMeter.jl
- test/test.jl
> Refactor @showprogress macro to support multidimensional loops

- README.md
- src/ProgressMeter.jl
- test/test.jl
Implements idea in #35 taking suggestions in #36 into account
> Custom Bar Glyphs

- src/ProgressMeter.jl
- test/runtests.jl
- test/test.jl
- test/test_showvalues.jl
This implements the feature request from https://github.com/timholy/ProgressMeter.jl/issues/40#issuecomment-216180088
I also added tests and there seems to be no regressions.
> Printing additional values below progress bar

- src/ProgressMeter.jl
> compatibility fix for Atom editor

- README.md
Documenting this PR: https://github.com/timholy/ProgressMeter.jl/pull/41
Discussed here: https://github.com/timholy/ProgressMeter.jl/issues/40
> Add `showvalues` example to README

- src/ProgressMeter.jl
> Change default output STDOUT by STDERR

- src/ProgressMeter.jl
> Change default output to stderr

- .travis.yml
ref https://github.com/travis-ci/travis-ci/issues/4942
> add git: depth option to workaround travis unshallow failure

- src/ProgressMeter.jl
> support color in IJulia, fix truncation

- .travis.yml
- REQUIRE
- src/ProgressMeter.jl
- test/test.jl
...and let femtocleaner do the rest
> Bump julia version and fix a few deprecations

- REQUIRE
- src/ProgressMeter.jl
- test/test.jl
* Use `Compat.Printf` for `@sprintf`
* Use `Compat.Test`
> Fixes for Julia 0.7

- src/ProgressMeter.jl
- test/test.jl
> Allow out-of-range calls to update!. Fixes #86.

- .travis.yml
- REQUIRE
- src/ProgressMeter.jl
- test/test.jl
- test/test_showvalues.jl
Just a few quick and easy fixes to make the tests stop complaining.
> Fix depreciations in tests

- src/ProgressMeter.jl
- test/test.jl
- used new iterator form
- used `seed!` instead of `srand`
> fixes for Julia 1.0

- REQUIRE
No urgent need for this, but why not? :slightly_smiling_face:
> Drop support for julia 0.7 prereleases

- README.md
- src/ProgressMeter.jl
- test/test.jl
- test/test_showvalues.jl
This addresses #101 from @tpapp.
I am not super happy with the naming, so if somebody has a better idea :)
> Add a progress meter with unspecified number of iterations.

- src/ProgressMeter.jl
- test/runtests.jl
- test/test_float.jl
> Added offset argument to allow for nested progress bars

- src/ProgressMeter.jl
- test/runtests.jl
- test/test_map.jl
I think this is uncontroversial enough to just merge without review once the tests pass. Happy to hear if anyone has any feedback though.
> fix #136 by adding yield in progress_map

- src/ProgressMeter.jl
- test/test.jl
I'd like to be able to specify where the progress meter should start so that I can continue a long-running process that is already half-finished.
> counterfirst

- src/ProgressMeter.jl
> Switch from spinlock to reentrantlock

- src/ProgressMeter.jl
- test/test.jl
> Nonparametric constructor for ProgressThresh

- src/ProgressMeter.jl
> Fix bar length update

- src/ProgressMeter.jl
- test/core.jl
- test/runtests.jl
> Add a performance test

- src/ProgressMeter.jl
It is sometimes useful to increase the progress by a step size larger than one, so I added an additional argument to next!() with the default value of 1.
> Allow arbitrary step size for next!()

- src/ProgressMeter.jl
- test/test_map.jl
> Allow pipes after a map

- src/ProgressMeter.jl
- test/test_map.jl
This one is pretty trivial, unless I'm missing something.
> @showprogress for asyncmap

- src/ProgressMeter.jl
> Only finish! once. Fix #199

- README.md
And break some long lines in the README.
> Add example of clock face symbols for spinner

- src/ProgressMeter.jl
- test/test.jl
> fix `@showprogress @distributed`

- src/ProgressMeter.jl
- test/core.jl
- test/test.jl
- test/test_threads.jl
taken from https://docs.julialang.org/en/v1/manual/interfaces/#man-interface-iteration
fixes #290
> add full iteration interface to ProgressWrapper

- src/ProgressMeter.jl
- test/test.jl
> don't round up to 100% if not finished

- README.md
Follow on from https://github.com/timholy/ProgressMeter.jl/pull/284
> update docs on `@showprogress` with threads

- .github/workflows/ci.yml
- Project.toml
I'll leave this up for a day in case anyone thinks this should be a minor bump (all the commits looked like fixes to me)
> ProgressMeter v1.10.0

- test/test_threads.jl
fix #338 
`threadid()` was only used in tests, to make sure that all threads are being used when testing
is there really a need to test how the threading is done?
> remove all `Threads.threadid()`

- Project.toml
- src/ProgressMeter.jl
Reverts timholy/ProgressMeter.jl#341
fix #343
> Revert "Fix printing of multiline values, and allow colors in showed values"
